# Use an official Python image as a base
FROM python:3.12

# Set the working directory to /app
WORKDIR /code

#
RUN pip install poetry

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt
RUN pip install kafka-python-stubs
RUN pip install poetry

# Copy the application code
COPY . /code/

# Expose the port the application will use
EXPOSE 8000

# Run the command to start the application
CMD ["poetry", "run", "uvicorn", "user.main:app", "--host", "0.0.0.0", "--reload"]