version: '3.9'

name: user

services:
  user-service:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:mashood@127.0.0.1:5432/mashood_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=user_events
    networks:
      - bridge

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mashood
      - POSTGRES_DB=mashood_db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bridge

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      zookeeper:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - zk-data:/var/lib/zookeeper/data

volumes:
  db-data:
  zk-data:
  POSTGRES_DB:
    driver: local

networks:
  default:
    driver: bridge